export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const FETCH_PAGINATED_QUESTIONS = "FETCH_PAGINATED_QUESTIONS";
export const FETCH_ALL_QUESTIONS = "FETCH_ALL_QUESTIONS";
export const FETCH_USER_QUESTIONS = "FETCH_USER_QUESTIONS";
export const ADD_QUESTION = "ADD_QUESTION";
export const FETCH_USER = "FETCH_USER";
